### ISSUE TITLE
[3주차] 복습과제 inline Q2. 관련 질문 있습니다.

### ISSUE THREAD

**Issue by memesoo99** [Ewha-Euron/Euron-AI-2021#14]
<img width="840" alt="스크린샷 2021-04-01 오후 5 43 29" src="https://user-images.githubusercontent.com/68745418/113267879-c728d080-9311-11eb-826f-4021db11a3a1.png">

위 식에서 픽셀 P(i,j)의 RGB채널은 고려안한건가요?? 아니면 채널을 고려했는데 그냥 표시를 생략한걸까요? 
아니면 혹시 픽셀이 흑백일때를 가정한건가요?

**Comment by leahincom** [comment]
위 식으로만 미루어 보면 채널은 고려하지 않은 것 같은데,
혹시 앞뒤 내용에 `skipped calculating 3 channels for brevity` 와 같은 내용이 포함되어 있진 않았나요? 어디선가 본 것 같아서...
출처 달아주시면 읽어보고 다시 코멘트 달겠습니다 :))

**Comment by memesoo99** [comment]
RGB 채널을 고려 안한거 같습니다! 답변 감사합니다
