### ISSUE TITLE
[1주차] history of computer vision(generalized cylinder, pictorial structure 등)관련 질문 있습니다.

### ISSUE THREAD

**Issue by songhee-cho** [Ewha-Euron/Euron-AI-2021#2]
history of computer vision(generalized cylinder, pictorial structure 등) 부분 질문 있습니다.

complex structure를 simple shape으로 나타내려는 노력들(generalized cylinder, pictorial structure 등)은 
연산량을 줄이기 위해서 연구된 내용인지 혹은 computer vision에서 물체를 기계가 이해할 수 있도록 만들기 위한 일종의 전처리를 시도한 것인지, 그 목적이 궁금합니다.

감사합니다.

**Comment by yskim0** [comment]
> 연산량을 줄이기 위해서 연구된 내용인지 혹은 computer vision에서 물체를 기계가 이해할 수 있도록 만들기 위한 일종의 전처리를 시도한 것인지

음 아예 다른 거라고 생각하시면 되는데, 이쯤에는 **Computer Vision이 어떤 일을 할 수 있을까를 고민한 시기입니다.**
이 시기쯤에는 컴퓨터는 매우 느리고, 심지어 많은 사람들이 소유하고 있지도 않았죠. 관련 환경이 모두 열악했기 때문에 **어떻게 대상을 인지하고 표현할지에 대한 고민을 한 시기라고 생각하시면 됩니다.**

그러다가 나온 게 질문 주신 두 가지 개념이죠.
generalized cylinder, pictorial structure는 **현실의 물체들(real-world structure)을 이해할 수 있도록 돕는 표현(representation) 방법**에 대한 얘기입니다.
또한 두 가지 모두 '모든 real-world objects들은 심플한 기하학적인 기본 요소들로 구성된다' 라는 것을 기반으로 하고 있습니다. 
우리가 인지하는 real-world objects들은 굉장히 복잡한 구조를 가지잖아요? 어떠한 것들이든 기하학적 요소를 통해 complex -> simple로 표현하는 것이죠.

**즉 연산량을 줄이기 위해도 아니고, 또 더욱이 컴퓨터가 이미지를 이해하게끔 하는 단계까지도 못 간 시기예요!**

**Comment by songhee-cho** [comment]
자세히 알려주셔서 정말 감사합니다~!
